stages: [lint, test]
image: python:3.12


variables:
PIP_DISABLE_PIP_VERSION_CHECK: "1"


before_script:
- python -V
- pip install -r requirements.txt -r requirements-dev.txt


lint:
stage: lint
script:
- flake8
- mypy app


tests:
stage: test
script:
- pytest -q --cov=app
artifacts:
when: always
reports:
junit: junit.xml
paths:
- .coverage