services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: microblog
      POSTGRES_USER: microblog
      POSTGRES_PASSWORD: microblog
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  app:
    build: .
    env_file: .env
    command: >
      sh -c "alembic upgrade head &&
             uvicorn app.main:app --host 0.0.0.0 --port 8000"
    depends_on:
      - db
    restart: unless-stopped

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      # сюда кладём СБОРКУ фронта (index.html, js, css)
      - ./frontend_dist:/usr/share/nginx/html:ro
      # наш конфиг nginx
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    restart: unless-stopped

volumes:
  pgdata:
